# Generated by Django 5.0.4 on 2024-04-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_dom', models.IntegerField(blank=True, null=True)),
                ('score_ext', models.IntegerField(blank=True, null=True)),
                ('equipe_dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='tournoisFoot.equipe')),
                ('equipe_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieur', to='tournoisFoot.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('equipes', models.ManyToManyField(related_name='tournois', to='tournoisFoot.equipe')),
            ],
        ),
    ]
