# Generated by Django 5.0.4 on 2024-04-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisFoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournoisFoot.tournoi'),
            preserve_default=False,
        ),
    ]
