# Generated by Django 5.0.4 on 2024-04-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisFoot', '0002_match_tournoi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score_dom',
            new_name='score_equipe1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_ext',
            new_name='score_equipe2',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe_dom',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe_ext',
        ),
        migrations.AddField(
            model_name='match',
            name='equipe1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipe1', to='tournoisFoot.equipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='equipe2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipe2', to='tournoisFoot.equipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='equipes',
            field=models.ManyToManyField(to='tournoisFoot.equipe'),
        ),
    ]
