# Generated by Django 5.0.4 on 2024-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisFoot', '0003_rename_score_dom_match_score_equipe1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='logo',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/5042/5042057.png'),
            preserve_default=False,
        ),
    ]
